blank_issues_enabled: false
contact_links:
  - name: Contact Blocks_n_more
    url: https://github.com/blocksnmore
    about: JSBoard Frontend & Backend developer
  - name: Contact Quick007
    url: https://github.com/quick007
    about: JSBoard Frontend developer
